name: aic
services:
  openpi_server:
    image: openpi_server_tpu
    build:
      context: ../openpi
      dockerfile: scripts/docker/serve_policy_tpu.Dockerfile
    privileged: true
    network_mode: host
    shm_size: 16gb
    cap_add:
      - ALL
    devices:
      - /dev:/dev
    environment:
      - SERVER_ARGS=policy:checkpoint --policy.config=pi05_ur5_aic --policy.dir=gs://openpi-assets/checkpoints/pi05_base
      - OPENPI_DATA_HOME=/openpi_assets
      - TPU_NAME=local
      - TF_CPP_MIN_LOG_LEVEL=0
      - XRT_TPU_CONFIG=localservice;0;localhost:51011
      - TF_XLA_FLAGS=--tf_xla_enable_xla_devices
      - PJRT_DEVICE=TPU
      - LD_LIBRARY_PATH=/lib
    volumes:
      - /mnt/disks/aic-challenge/aic/openpi/.venv/lib/python3.11/site-packages/libtpu/libtpu.so:/lib/libtpu.so
      - ../openpi:/app
  eval:
    image: ghcr.io/intrinsic-dev/aic/aic_eval
    # build:
    #   dockerfile: docker/aic_eval/Dockerfile
    #   context: ..
    volumes:
      - /mnt/disks/aic-challenge/aic_results:/root/aic_results
      - /mnt/disks/aic-challenge/aic/aic_description/world/aic.sdf:/ws_aic/install/share/aic_description/world/aic.sdf
      - /mnt/disks/aic-challenge/aic/aic_bringup/config/ros_gz_bridge_config.yaml:/ws_aic/install/share/aic_bringup/config/ros_gz_bridge_config.yaml
      - /mnt/disks/aic-challenge/aic/aic_engine/config/sample_config.yaml:/ws_aic/install/share/aic_engine/config/sample_config.yaml
    command: gazebo_gui:=false launch_rviz:=false ground_truth:=false start_aic_engine:=true shutdown_on_aic_engine_exit:=true
    networks:
      - default
    environment:
      AIC_EVAL_PASSWD: CHANGE_IN_PROD
      AIC_MODEL_PASSWD: CHANGE_IN_PROD
  model:
    image: my-solution:v1
    build:
      dockerfile: docker/aic_model/Dockerfile
      context: ..
    networks:
      - default
    command: --ros-args -p policy:=aic_example_policies.ros.RunOpenPIBase_latest -p openpi_host:=${OPENPI_HOST_IP:-openpi_server}
    environment:
      RMW_IMPLEMENTATION: rmw_zenoh_cpp
      ZENOH_ROUTER_CHECK_ATTEMPTS: -1
      AIC_ROUTER_ADDR: eval:7447
      AIC_MODEL_PASSWD: CHANGE_IN_PROD
networks:
  default: {}
#    internal: true
